name: e-health

services:
  # BEGIN: Microservices

  # Gateway
  frontdoor:
    container_name: e-health-frontdoor
    build:
      context: ./frontdoor
      dockerfile: ../Dockerfile

    env_file:
      - ./frontdoor/.env

    ports:
      - 8000:8000

    volumes:
      - ./frontdoor/build/libs/frontdoor-0.0.1-SNAPSHOT.jar:/app/e-health.jar

  # Auth
  gatekeeper:
    container_name: e-health-gatekeeper
    build:
      context: ./gatekeeper
      dockerfile: ../Dockerfile

    env_file:
      - ./gatekeeper/.env
    ports:
      - 8001:8001

    volumes:
      - ./gatekeeper/build/libs/gatekeeper-0.0.1-SNAPSHOT.jar:/app/e-health.jar

  # Employee
  hr:
    container_name: e-health-hr
    build:
      context: ./hr
      dockerfile: ../Dockerfile

    env_file:
      - ./hr/.env

    ports:
      - 8002:8002

    volumes:
      - ./hr/build/libs/hr-0.0.1-SNAPSHOT.jar:/app/e-health.jar

  # Patient
  ward:
    container_name: e-health-ward
    build:
      context: ./ward
      dockerfile: ../Dockerfile

    env_file:
      - ./ward/.env

    ports:
      - 8003:8003

    volumes:
      - ./ward/build/libs/ward-0.0.1-SNAPSHOT.jar:/app/e-health.jar

  # Pharmacy
  rx:
    container_name: e-health-rx
    build:
      context: ./rx
      dockerfile: ../Dockerfile

    env_file:
      - ./rx/.env

    ports:
      - 8004:8004

    volumes:
      - ./rx/build/libs/rx-0.0.1-SNAPSHOT.jar:/app/e-health.jar
