name: e-health

services:
  frontdoor:
    container_name: e-health-frontdoor
    build:
      context: ./frontdoor
      dockerfile: ../Dockerfile

    env_file:
      - ./frontdoor/.env

    ports:
      - 8000:8000

    volumes:
      - ./frontdoor/build/libs/frontdoor-0.0.1-SNAPSHOT.jar:/app/e-health.jar

  gatekeeper:
    container_name: e-health-gatekeeper
    build:
      context: ./gatekeeper
      dockerfile: ../Dockerfile

    env_file:
      - ./gatekeeper/.env
    ports:
      - 8001:8001

    volumes:
      - ./gatekeeper/build/libs/gatekeeper-0.0.1-SNAPSHOT.jar:/app/e-health.jar

    depends_on:
      authdb:
        condition: service_healthy

  hr:
    container_name: e-health-hr
    build:
      context: ./hr
      dockerfile: ../Dockerfile

    env_file:
      - ./hr/.env

    ports:
      - 8002:8002

    volumes:
      - ./hr/build/libs/hr-0.0.1-SNAPSHOT.jar:/app/e-health.jar

    depends_on:
      hrdb:
        condition: service_healthy

  # Microservice Databases
  authdb:
    container_name: e-health-auth-db
    image: postgres:17.1-alpine
    ports:
      - 5432:5432
    
    volumes:
      - ./authdb-ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth

  hrdb:
    container_name: e-health-hr-db
    image: postgres:17.1-alpine
    ports:
      - 5433:5432

    volumes:
      - ./hrdb-ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hr
