name: e-health

services:
  # BEGIN: Microservices

  # Gateway
  frontdoor:
    container_name: e-health-frontdoor
    build:
      context: ./frontdoor
      dockerfile: ../Dockerfile

    env_file:
      - ./frontdoor/.env

    ports:
      - 8000:8000
      - 5000:5005

    develop:
      watch:
        - action: sync+restart
          path: ./frontdoor/build/libs/frontdoor-0.0.1-SNAPSHOT.jar
          target: /app/e-health.jar

  # Auth
  gatekeeper:
    container_name: e-health-gatekeeper
    build:
      context: ./gatekeeper
      dockerfile: ../Dockerfile

    env_file:
      - ./gatekeeper/.env

    ports:
      - 8001:8001
      - 5001:5005

    develop:
      watch:
        - action: sync+restart
          path: ./gatekeeper/build/libs/gatekeeper-0.0.1-SNAPSHOT.jar
          target: /app/e-health.jar

  # Employee
  hr:
    container_name: e-health-hr
    build:
      context: ./hr
      dockerfile: ../Dockerfile

    env_file:
      - ./hr/.env

    ports:
      - 8002:8002
      - 5002:5005

    develop:
      watch:
        - action: sync+restart
          path: ./hr/build/libs/hr-0.0.1-SNAPSHOT.jar
          target: /app/e-health.jar

  # Patient
  ward:
    container_name: e-health-ward
    build:
      context: ./ward
      dockerfile: ../Dockerfile

    env_file:
      - ./ward/.env

    ports:
      - 8003:8003
      - 5003:5005

    develop:
      watch:
        - action: sync+restart
          path: ./ward/build/libs/ward-0.0.1-SNAPSHOT.jar
          target: /app/e-health.jar

  # Pharmacy
  rx:
    container_name: e-health-rx
    build:
      context: ./rx
      dockerfile: ../Dockerfile

    env_file:
      - ./rx/.env

    ports:
      - 8004:8004
      - 5004:5005

    develop:
      watch:
        - action: sync+restart
          path: ./rx/build/libs/rx-0.0.1-SNAPSHOT.jar
          target: /app/e-health.jar
