server:
  port: 8003
  error:
    include-message: always
    include-binding-errors: always

  servlet:
    context-path: /api/ward

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
        data:
          rest: debug

spring:
  application:
    name: Ward

  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}

  jackson:
    time-zone: UTC
    mapper:
      "[ACCEPT_CASE_INSENSITIVE_ENUMS]": true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  rsa:
    public-key: classpath:certs/public-key.pem
