name: Build Workflow

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
        description: Service name

      auth:
        default: false
        type: boolean
        description: Marks if the service sign JWT tokens

jobs:
  build:
    name: Build Jar and Dockerize
    runs-on: ubuntu-latest
    steps:
      # BEGIN - Enviroment setup
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      # END - Enviroment setup

      # BEGIN - Gradle build tasks
      - name: Build the app
        run: ./gradlew clean :${{ inputs.service }}:build

      # END - Gradle build tasks

      # BEGIN - Docker setup
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # END - Docker setup

      # BEGIN - Docker build
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ github.workspace }}/${{ inputs.service }}
          file: ci.Dockerfile
          push: true
          tags: rockspringa/e-health:${{ inputs.service }}-latest

      # END - Docker build
