name: Deploy

on:
  workflow_run:
    workflows:
      - Build frontdoor service
      - Build gatekeeper service
      - Build hr service
      - Build rx service
      - Build ward service

    branches:
      - main

    types:
      - completed

jobs:
  deploy:
    name: Cloud Run Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      SERVICE_NAME: ${ echo ${{ github.event.workflow_run.name }} | cut -d ' ' -f2 | tr a-z A-Z }

    steps:
      # BEGIN - Enviroment setup
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo ${{ secrets[format('{0}_ENV', env.SERVICE_NAME)] }} > .env 

      # END - Enviroment setup

      # BEGIN - GCP setup
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # END - GCP setup

      # BEGIN - Deploy
      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: ${{ secrets.GCP_SERVICE }}
          image: "rockspringa/e-health:${{ env.SERVICE_NAME }}-latest"
          env_vars_file: .env

      # END - Deploy
